### ISSUE TITLE
Display port

### ISSUE THREAD

**Issue by ea7gwc** [AndyTaylorTweet/Pi-Star_DV_Dash#106]
Hi, I just updated and the screen port selection doesn't work.
Regards.

**Comment by ea7gwc** [comment]
Sorry if it works but USB0 doesn't come out.

**Comment by AndyTaylorTweet** [comment]
working on it

**Comment by ea7gwc** [comment]
![image](https://user-images.githubusercontent.com/27195724/82585312-1781be80-9b96-11ea-8fed-db308ff95d83.png)
I can't choose USB0, it comes out blank.
For it to come out, I have to edit it directly
MMDVMHost in expert.

**Comment by ea7gwc** [comment]
OK thank you, I see you have already seen it

**Comment by AndyTaylorTweet** [comment]
Update and re-test pls. If you have a serial device connected to the Pi when you go to the config page, it should show them now...

**Comment by AndyTaylorTweet** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/18753260/82586383-5d875400-9b8f-11ea-851c-5391121ca7c4.png">

**Comment by AndyTaylorTweet** [comment]
ok its still not working right... urgh

**Comment by ea7gwc** [comment]
Now if it exits and it works, in mmdvmhost ini write
the correct port, but on the configuration page
the indication is none
![image](https://user-images.githubusercontent.com/27195724/82587994-6af60b80-9b9a-11ea-8eac-0c21acbf95de.png)
![image](https://user-images.githubusercontent.com/27195724/82588066-8234f900-9b9a-11ea-9652-af23053b6550.png)

**Comment by ea7gwc** [comment]
![image](https://user-images.githubusercontent.com/27195724/82588783-89103b80-9b9b-11ea-8820-33abda903e4d.png)
Now it seems correct, although when displaying the list
USB0 appears 2 times

**Comment by AndyTaylorTweet** [comment]
ok now its working correctly even if you pick "None" (that was having very strange effects)..
the selected port is showing twice yes, but I can live with that, if I try to make it only show once, it can remove the port when the device isnt present...
