### ISSUE TITLE
Semi-colon missing from HTML use of "&infin"

### ISSUE THREAD

**Issue by victorchong** [AndyTaylorTweet/Pi-Star_DV_Dash#109]
Facebook user "Din Kaftac" reports "TX &infin sec" message in gateway activity display. Looks like the semicolon is missing from the HTML for the infinity symbol.

mmdvmhost/lh.php:line 69 - needs semicolon after "&infin",
i.e. $duration_string = $duration<999 ? round($duration) . "+" : "&amp;infin;";

mmdvmhost/localtx.php:line 66 - needs semicolon after "&infin"
i.e. $duration_string = $duration<999 ? round($duration) . "+" : "&amp;infin;";

![101513763_3085689711451440_4601328326835961856_o](https://user-images.githubusercontent.com/62109882/83926820-d534b180-a73f-11ea-9774-5014ee10bbcf.jpg)

**Comment by AndyTaylorTweet** [comment]
Thank you - fixed :)
