### ISSUE TITLE
Open to PR for API endpoints?

### ISSUE THREAD

**Issue by jamescurtin** [AndyTaylorTweet/Pi-Star_DV_Dash#123]
Thanks for this great project!

I'm interested in exporting structured data from my Pi-Star to other devices on my network. All of the information I need can be found on the dashboards, though it'd be preferable if the device provided an API to avoid the need for HTML parsing.

Would you be willing to review PR(s) that add an `api` directory with endpoints that publish parts of the dashboard as JSON?

**Comment by AndyTaylorTweet** [comment]
Yes of course
