### ISSUE TITLE
Updater script should use sync instead of waiting

### ISSUE THREAD

**Issue by DC7IA** [AndyTaylorTweet/Pi-Star_DV_Dash#126]
Hi,

not sure if this is the correct repository.

I just noticed the Pi-Star Updater giving out the following output:

```
Updates complete, sleeping for a few seconds before making the disk Read-Only
Finished
```

Instead of waiting, I'd like to suggest using the `sync` command.

I mean... There's the potential for data loss if writing takes longer than the time waiting. :)

**Comment by hammyMarc** [comment]
Upvote for this feature request.

**Comment by DC7IA** [comment]
> Upvote for this feature request.

I'd not consider it a feature request, but a bug fix.

**Comment by AndyTaylorTweet** [comment]
This is the dashboard, not where the update script lives - that asside, script modified to use sync ( 3 times just in case :) )
