### ISSUE TITLE
P25 settings server cannot be saved

### ISSUE THREAD

**Issue by PretendTesting** [AndyTaylorTweet/Pi-Star_DV_Dash#132]
I am pi-star ver 3.4.17 Dashboard ver 20210224
Later I checked the code and I found the reason, but I didn't understand why it was designed this way.
![QQ截图20210228161159](https://user-images.githubusercontent.com/17795712/109412008-9dae1980-79e0-11eb-9db2-b786b4ed0084.png)

BI1IZF
73

**Comment by AndyTaylorTweet** [comment]
It's a simple check to make sure the new config is at least 30 lines long, if its not, don't save it because there is a problem with it.

**Comment by PretendTesting** [comment]
Thank you for your answer. How can I get the correct configuration file? Can I copy a 4.1.X configuration file to replace it?

**Comment by AndyTaylorTweet** [comment]
```
[General]
Callsign=M1ABC
RptAddress=127.0.0.1
RptPort=32010
LocalPort=42020
Announcements=1
Daemon=1

[Id Lookup]
Name=/usr/local/etc/DMRIds.dat
Time=24

[Log]
FilePath=/var/log/pi-star
FileRoot=P25Gateway

[Network]
Port=42010
HostsFile1=/usr/local/etc/P25Hosts.txt
HostsFile2=/usr/local/etc/P25HostsLocal.txt
ReloadTime=60
ParrotAddress=127.0.0.1
ParrotPort=42011
#Startup=
Debug=0

[Voice]
Enabled=1
Language=en_GB
Directory=/usr/local/etc/P25_Audio
```

Above is en example file.

**Comment by PretendTesting** [comment]
Thank you

BI1IZF
73
