### ISSUE TITLE
Please fix this bug regarding periods in wifi.php code

### ISSUE THREAD

**Issue by n3gwg** [AndyTaylorTweet/Pi-Star_DV_Dash#178]
Andy, et alia:

I finally found Chip's code that fixed this bug and I would thus very respectfully request that it be added into the Pi-Star source code. I would suggest someone review the IEEE standard for characters allowed in a WiFi SSID and assure that all are supported in these lines of code.

https://repo.w0chp.net/WPSD-Dev/W0CHP-PiStar-Dash/commit/99c14bf387d625786dd993d6375f716427b36706

The file //var/www/dashboard/admin/wifi.php is where the modification should be made.

103c103
< if (preg_match('/ESSID:\"([a-zA-Z0-9-._\s]+)\"/i',$strWlan0,$result)) {
---
> if (preg_match('/ESSID:\"([a-zA-Z0-9-_\s]+)\"/i',$strWlan0,$result)) {
105c105
< if (preg_match('/SSID:\ ([a-zA-Z0-9-._\s]+)/i',$strWlan0,$result)) {
---
> if (preg_match('/SSID:\ ([a-zA-Z0-9-_\s]+)/i',$strWlan0,$result)) {

73,
Stuart, N3GWG

**Comment by MW0MWZ** [comment]
Done.

**Comment by n3gwg** [comment]
Andy,

Thank you sir!

I also posted in my "New Releases" post a number of other concerns I found in the current Pi-Star as well.

73,
Stuart, N3GWG
