### ISSUE TITLE
DMR Gateway config and multiple *Rewrite rules 

### ISSUE THREAD

**Issue by f1rmb** [AndyTaylorTweet/Pi-Star_DV_Dash#51]
Hi,
   Since I refuse to have anything to do with Facebook, I report this problem here.
At the first place, many thanks for this nice piece of software, it works like a treat.

It seems that multiple rewrite rules (per section) doesn't work:

Example with a DMR and D-Star enabled hotspot:
  (full edit in expert mode) 
   - Define two PCRewrite rules in a DMR section,
   - Turn off D-Star mode
   - Just a single PCRewrite rule survive.

Also, if two *Rewrite rules are defined, the DMR GW quick edit will handle only one *Rewrite rule.

Cheers.
---
Daniel

**Comment by AndyTaylorTweet** [comment]
Yes - I updated the factory configs to account for this - restore a factory config to see the new numbered re-write rules - those will survive now :)

Factory config also allows TS1 through DMR Gateway.

**Comment by f1rmb** [comment]
Excellent, I will update ASAP

Many thanks for your support Andy.

Vy 73!
---
Daniel

**Comment by f1rmb** [comment]
I close the issue, everything is working perfectly.

Thanks Andy.
