### ISSUE TITLE
Add url link for DAPNET callsign 

### ISSUE THREAD

**Issue by sp2ong** [AndyTaylorTweet/Pi-Star_DV_Dash#53]
Hi,

It will be nice add url link in a dashboard for callsign DAPNET 

https://hampager.de/#/transmitters/map

like another callsign has url link to QRZ.com

**Comment by AndyTaylorTweet** [comment]
So far as I know there is no simple dapnet lookup at this time.

**Comment by sp2ong** [comment]
Hi,

I thought only of a simple solution at current:
`
if (is_numeric($listElem[2]) || $listElem[2] == "DAPNET") {
			echo "<td align=\"left\"><a href=\"https://hampager.de/#/transmitters/map\" target=\"_blank\">$listElem[2]</a></td>";
`

**Comment by sp2ong** [comment]
Hi,

Maybe better this:
`
		if (is_numeric($listElem[2]) && $listElem[2] == "DAPNET") {
			echo "<td align=\"left\"><a href=\"https://hampager.de/#/transmitters/map\" target=\"_blank\">$listElem[2]</a></td>"; }
		if (is_numeric($listElem[2])) {
			echo "<td align=\"left\">$listElem[2]</td>";
		} else {
...
`
