### ISSUE TITLE
Request: Can github tags be included with releases?

### ISSUE THREAD

**Issue by JDogHerman** [AndyTaylorTweet/Pi-Star_DV_Dash#6]
Tags would allow people to see quickly what version of code the repo is on without having to navigate to the versions file.

**Comment by AndyTaylorTweet** [comment]
The repo is a rolling release - I dont build individual releases - so every Pi-Star is running exactly the code you see here.

The new Repo's V3/V4 are not in production at this time.

**Comment by JDogHerman** [comment]
I was just hoping to be able to see what version of the code was published via the tags.

**Comment by AndyTaylorTweet** [comment]
What you see in the repo *is* the live / published version, there are no forks / tags / releases - what you see in here is what lands on your Pi during the update process.
