### ISSUE TITLE
cosmetic error in /etc/motd http://pi-star-dstar/

### ISSUE THREAD

**Issue by sgtsmall** [AndyTaylorTweet/Pi-Star_DV_Dash#69]
Very minor cosmetic change required in image source.

current motd has text ... Pi_star logo
...
From your Windows Computer:
Pi-Star Dashboard:      http://pi-star-dstar/

From your Apple iPhone, iPad, Macbook, iMac etc.
Pi-Star Dashboard:      http://pi-star-dstar.local/

Pi-Star's disk is read-only by default, enable read-write with "rpi-rw".
Pi-Star built by Andy Taylor (MW0MWZ), pi-star-dstar tools all start "pistar-".

cat /etc/hostname
pi-star

configure.php has 
...
	  $currHostname = exec('cat /etc/hostname');
	  $rollHostname = 'sudo sed -i "s/'.$currHostname.'/'.$newHostnameLower.'/" /etc/hostname';
	  $rollHosts = 'sudo sed -i "s/'.$currHostname.'/'.$newHostnameLower.'/" /etc/hosts';
	  $rollMotd = 'sudo sed -i "s/'.$currHostname.'/'.$newHostnameLower.'/" /etc/motd';

Recommend changing /etc/motd text on image source to:

...
From your Windows Computer:
Pi-Star Dashboard:      http://pi-star/

From your Apple iPhone, iPad, Macbook, iMac etc.
Pi-Star Dashboard:      http://pi-star.local/

Pi-Star's disk is read-only by default, enable read-write with "rpi-rw".
Pi-Star built by Andy Taylor (MW0MWZ), pi-star tools all start "pistar-".

**Comment by AndyTaylorTweet** [comment]
This has already been cured in the current images.

**Comment by sgtsmall** [comment]
excellent
