### ISSUE TITLE
WPA_Supplicant always being set to JP country code

### ISSUE THREAD

**Issue by kc7ngc** [AndyTaylorTweet/Pi-Star_DV_Dash#92]
Every time a new access point is added via WIFI configuration dashboard the wpa_supplicant config is being rewritten and is setting country=JP.  Which is setting wrong frequencies for devices with 5ghz radios causing connectivity issues for some raspberry pi's.

Dashboard should allow people to select their country region and use that instead of using a hidden hard coded default.

/var/www/dashboard/admin/wifi.php

`if(isset($_POST['SaveWPAPSKSettings'])) {
                $config = "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev\nupdate_config=1\nap_scan=1\nfast_reauth=1\ncountry=JP\n\n";
                $networks = $_POST['Networks'];`

**Comment by AndyTaylorTweet** [comment]
JP *was* sane when we lived in a world where Pi boards only ever had 2.4GHz wifi, that is no longer the case, so thanks for the reminder. I have now patched the wifi code to allow you to set the country correctly. Let me know how you get on.

Andy

**Comment by kc7ngc** [comment]
Ideally you should be getting the regional codes for the select from the crda database and not the 
from /usr/share/zoneinfo/zone.tab file as zones don't always directly map to regulatory domains.   There are many more zones than regulatory domains in the crda database.

I think something like this would work as a drop in replacement for your enumerations of the regulatory domains:

`regdbdump` /lib/crda/regulatory.bin  | fgrep country | cut -b 9-10`

Which should allow them to only select regulatory domains that are valid crda entries.

I haven't gone through and looked at all of the commits or test it and won't be home till later.  Will give it a try this weekend after I back get a backup of my hotspot.

**Comment by AndyTaylorTweet** [comment]
Originally I did it the other way to provide plain names along with the country code, but I can't disagree, there were more entries than in the regulatory.bin - and I could really use not adding more issues... so I'll modify this with your suggestion.

**Comment by kc7ngc** [comment]
If you really want the names there you could always populate the country names when doing the select building loop by querying the zonetab file.  In theory something like this: (this is not true php as was having trouble with editor no here mangling it, but its close)

`exec('grep "regdbdump /lib/crda/regulatory.bin | fgrep country | cut -b 9-10`', $regDomains);
		foreach($regDomains as $regDomain) {
                         exec('grep ^'.$regDomain.' /usr/share/zoneinfo/zone.tab | cut  -f3',$countrynames);
                         if (strlen($countrynames[0])>0) {
                                   $countrytext = $countrynames[0];
                         } else {
                                   $countrytext = "Undefined";
                        }
                          $output .= 'option value="'.$regDomain].'">'.$regDomain.' - '.$countrytext.'/option'."\n";
.....etc.
}

`

**Comment by AndyTaylorTweet** [comment]
Honestly I can live without it at this point - I had the same idea about using a loop to populate the names, but I dont think its worth it, however maybe I'll add that later if its needed.

**Comment by kc7ngc** [comment]
So been testing this on my systems and things seem to be working pretty well.   Going to close this out.  Thanks for all the good work.

**Comment by kc7ngc** [comment]
So been testing this on my systems and things seem to be working pretty well. Going to close this out. Thanks for all the good work.
