### ISSUE TITLE
ysfgateway Startup format not correct after update Dashboard: 20200221

### ISSUE THREAD

**Issue by bi7jta** [AndyTaylorTweet/Pi-Star_DV_Dash#96]
Hello Andy,
When I choose  YSF Startup Host: YSF80337 - CN China #1 - W24166/TG46001,
the pi-star php application will save 
the error format to the ysfgateway config file, as follow,
Startup CN China \#1
the correct :
Startup CN China #1
Pi-Star:3.4.17 / Dashboard: 20200221

Please fix it  ,thanks!

DE BI7JTA

**Comment by AndyTaylorTweet** [comment]
Fixed up (removed the hash marks).

**Comment by bi7jta** [comment]
Thank you very much ,have tested and fixed.
73 DE BI7JTA
