### ISSUE TITLE
DMR GW configuration is escaping already escaped characters

### ISSUE THREAD

**Issue by RafaelGCPP** [AndyTaylorTweet/Pi-Star_DV_Dash#98]
If the BrandMeister hotspot security password contains non-alphanumeric characters (e.g., !@#$%&) the password is escaped before saving it to the .ini file. When the page is reloaded, the page load escapes the string again, and that blocks access to BrandMeister network.

**Step to reproduce:**

- Set DMR master to DMRGateway
- Set BM Hotspot security to Test#1234
- Apply changes

In the /etc/dmrgateway, the following line will be written;
Password=Test\\\#1234

- Now, toggle BrandMeister Network enable and apply changes

In the /etc/dmrgateway, the password now reads;
Password=Test\\\\\\#1234

**Possible culprit:**

In configure.php, line 1009, the newly set password is escaped

$configModem['BrandMeister']['Password'] = escapeshellcmd($_POST['bmHSSecurity']);

Then in configure.php, line 3174, the password field is filled with the content of the configuration file, which is already escaped.

\<input type="password" name="bmHSSecurity" size="30" maxlength="30" value="\<?php if (isset($configModem['BrandMeister']['Password'])) {echo $configModem['BrandMeister']['Password'];} ?>">\</input>

**Comment by AndyTaylorTweet** [comment]
thank you - I will take a look at this...

**Comment by AndyTaylorTweet** [comment]
OK give that a shot, I have made sure that the variable ends up in quotes, that should work for anything other than a string that includes quotes, but I can add javascript to detect that instead.

Please update and test it.

**Comment by RafaelGCPP** [comment]
It seems to be working. Thanks for the quick fix!
